from typing import Dict, Union, Iterable


class PubSub:
    def subscribe(self, *args: str, **kwargs: str) -> int: ...

    def unsubscribe(self, *args: str) -> int: ...

    def close(self) -> None: ...

    def get_message(self, ignore_subscribe_messages: bool = False, timeout: int = 0) -> Dict[str, Union[bytes, str, int, None]]: ...

    def listen(self) -> Iterable: ...
